import sharp from 'sharp';
import { readdir, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const manifest = {};
let originalBytes = 0, fullBytes = 0, mobileBytes = 0;
for (const language of ['RU', 'EN']) {
  const source = `public/assets/preview/${language}`;
  const output = `public/assets/preview-optimized/${language}`;
  await mkdir(output, { recursive: true });
  for (const name of (await readdir(source)).filter(name => name.endsWith('.png')).sort()) {
    const original = await readFile(path.join(source, name));
    const screen = name.slice(0, -4);
    const full = await sharp(original).webp({ lossless: true, effort: 6 }).toBuffer();
    const mobile = await sharp(original).resize(1024, 542).webp({ nearLossless: true, quality: 85, effort: 6 }).toBuffer();
    const useWebp = full.length < original.length;
    if (useWebp) await writeFile(path.join(output, `${screen}.webp`), full);
    await writeFile(path.join(output, `${screen}-mobile.webp`), mobile);
    manifest[`${language}/${screen}`] = {
      full: useWebp ? `/assets/preview-optimized/${language}/${screen}.webp` : `/assets/preview/${language}/${name}`,
      mobile: `/assets/preview-optimized/${language}/${screen}-mobile.webp`,
    };
    originalBytes += original.length;
    fullBytes += useWebp ? full.length : original.length;
    mobileBytes += mobile.length;
  }
}
await writeFile('src/image-manifest.ts', `// Generated by npm run images. Do not edit by hand.\nexport const imageManifest: Record<string, { full: string; mobile: string }> = ${JSON.stringify(manifest, null, 2)};\n`);
console.log(JSON.stringify({ originalBytes, fullBytes, mobileBytes, fullSavingPercent: Math.round((1 - fullBytes / originalBytes) * 100), mobileSavingPercent: Math.round((1 - mobileBytes / originalBytes) * 100) }, null, 2));
