// Generated by npm run images. Do not edit by hand.
export const imageManifest: Record<string, { full: string; mobile: string }> = {
  "RU/Discover": {
    "full": "/assets/preview-optimized/RU/Discover.webp",
    "mobile": "/assets/preview-optimized/RU/Discover-mobile.webp"
  },
  "RU/Home": {
    "full": "/assets/preview-optimized/RU/Home.webp",
    "mobile": "/assets/preview-optimized/RU/Home-mobile.webp"
  },
  "RU/Library": {
    "full": "/assets/preview-optimized/RU/Library.webp",
    "mobile": "/assets/preview-optimized/RU/Library-mobile.webp"
  },
  "RU/Library_Pressed-Instances": {
    "full": "/assets/preview/RU/Library_Pressed-Instances.png",
    "mobile": "/assets/preview-optimized/RU/Library_Pressed-Instances-mobile.webp"
  },
  "RU/New-Instances": {
    "full": "/assets/preview-optimized/RU/New-Instances.webp",
    "mobile": "/assets/preview-optimized/RU/New-Instances-mobile.webp"
  },
  "RU/S-Accounts": {
    "full": "/assets/preview-optimized/RU/S-Accounts.webp",
    "mobile": "/assets/preview-optimized/RU/S-Accounts-mobile.webp"
  },
  "RU/S-Advanced": {
    "full": "/assets/preview-optimized/RU/S-Advanced.webp",
    "mobile": "/assets/preview-optimized/RU/S-Advanced-mobile.webp"
  },
  "RU/S-Appearance": {
    "full": "/assets/preview-optimized/RU/S-Appearance.webp",
    "mobile": "/assets/preview-optimized/RU/S-Appearance-mobile.webp"
  },
  "RU/S-Console": {
    "full": "/assets/preview-optimized/RU/S-Console.webp",
    "mobile": "/assets/preview-optimized/RU/S-Console-mobile.webp"
  },
  "RU/S-Downloads": {
    "full": "/assets/preview-optimized/RU/S-Downloads.webp",
    "mobile": "/assets/preview-optimized/RU/S-Downloads-mobile.webp"
  },
  "RU/S-General": {
    "full": "/assets/preview-optimized/RU/S-General.webp",
    "mobile": "/assets/preview-optimized/RU/S-General-mobile.webp"
  },
  "RU/S-Java": {
    "full": "/assets/preview-optimized/RU/S-Java.webp",
    "mobile": "/assets/preview-optimized/RU/S-Java-mobile.webp"
  },
  "RU/S-Minecraft": {
    "full": "/assets/preview-optimized/RU/S-Minecraft.webp",
    "mobile": "/assets/preview-optimized/RU/S-Minecraft-mobile.webp"
  },
  "RU/S-Notifications": {
    "full": "/assets/preview-optimized/RU/S-Notifications.webp",
    "mobile": "/assets/preview-optimized/RU/S-Notifications-mobile.webp"
  },
  "RU/S-Privacy": {
    "full": "/assets/preview-optimized/RU/S-Privacy.webp",
    "mobile": "/assets/preview-optimized/RU/S-Privacy-mobile.webp"
  },
  "RU/S-Storage": {
    "full": "/assets/preview-optimized/RU/S-Storage.webp",
    "mobile": "/assets/preview-optimized/RU/S-Storage-mobile.webp"
  },
  "RU/S-Sync": {
    "full": "/assets/preview-optimized/RU/S-Sync.webp",
    "mobile": "/assets/preview-optimized/RU/S-Sync-mobile.webp"
  },
  "EN/Discover": {
    "full": "/assets/preview-optimized/EN/Discover.webp",
    "mobile": "/assets/preview-optimized/EN/Discover-mobile.webp"
  },
  "EN/Home": {
    "full": "/assets/preview-optimized/EN/Home.webp",
    "mobile": "/assets/preview-optimized/EN/Home-mobile.webp"
  },
  "EN/Library": {
    "full": "/assets/preview-optimized/EN/Library.webp",
    "mobile": "/assets/preview-optimized/EN/Library-mobile.webp"
  },
  "EN/Library_Pressed-Instances": {
    "full": "/assets/preview/EN/Library_Pressed-Instances.png",
    "mobile": "/assets/preview-optimized/EN/Library_Pressed-Instances-mobile.webp"
  },
  "EN/New-Instances": {
    "full": "/assets/preview-optimized/EN/New-Instances.webp",
    "mobile": "/assets/preview-optimized/EN/New-Instances-mobile.webp"
  },
  "EN/S-Accounts": {
    "full": "/assets/preview-optimized/EN/S-Accounts.webp",
    "mobile": "/assets/preview-optimized/EN/S-Accounts-mobile.webp"
  },
  "EN/S-Advanced": {
    "full": "/assets/preview-optimized/EN/S-Advanced.webp",
    "mobile": "/assets/preview-optimized/EN/S-Advanced-mobile.webp"
  },
  "EN/S-Appearance": {
    "full": "/assets/preview-optimized/EN/S-Appearance.webp",
    "mobile": "/assets/preview-optimized/EN/S-Appearance-mobile.webp"
  },
  "EN/S-Console": {
    "full": "/assets/preview-optimized/EN/S-Console.webp",
    "mobile": "/assets/preview-optimized/EN/S-Console-mobile.webp"
  },
  "EN/S-Downloads": {
    "full": "/assets/preview-optimized/EN/S-Downloads.webp",
    "mobile": "/assets/preview-optimized/EN/S-Downloads-mobile.webp"
  },
  "EN/S-General": {
    "full": "/assets/preview-optimized/EN/S-General.webp",
    "mobile": "/assets/preview-optimized/EN/S-General-mobile.webp"
  },
  "EN/S-Java": {
    "full": "/assets/preview-optimized/EN/S-Java.webp",
    "mobile": "/assets/preview-optimized/EN/S-Java-mobile.webp"
  },
  "EN/S-Minecraft": {
    "full": "/assets/preview-optimized/EN/S-Minecraft.webp",
    "mobile": "/assets/preview-optimized/EN/S-Minecraft-mobile.webp"
  },
  "EN/S-Notifications": {
    "full": "/assets/preview-optimized/EN/S-Notifications.webp",
    "mobile": "/assets/preview-optimized/EN/S-Notifications-mobile.webp"
  },
  "EN/S-Privacy": {
    "full": "/assets/preview-optimized/EN/S-Privacy.webp",
    "mobile": "/assets/preview-optimized/EN/S-Privacy-mobile.webp"
  },
  "EN/S-Storage": {
    "full": "/assets/preview-optimized/EN/S-Storage.webp",
    "mobile": "/assets/preview-optimized/EN/S-Storage-mobile.webp"
  },
  "EN/S-Sync": {
    "full": "/assets/preview-optimized/EN/S-Sync.webp",
    "mobile": "/assets/preview-optimized/EN/S-Sync-mobile.webp"
  }
};
